package cli

// adbCommands is the list of native adb subcommands used for shell completion.
// This list mirrors the ALL_ADB_COMMANDS array in zsh's _adb completion function
// and should be updated when adb adds new subcommands.
var adbCommands = []string{
	"attach",
	"backup",
	"bugreport",
	"clear-data",
	"completion",
	"connect",
	"detach",
	"device",
	"devices",
	"disable-verity",
	"disconnect",
	"emu",
	"enable-verity",
	"exec-out",
	"forward",
	"get-devpath",
	"get-serialno",
	"get-state",
	"help",
	"install",
	"install-multiple",
	"install-multi-package",
	"jdwp",
	"keygen",
	"kill-server",
	"launch",
	"logcat",
	"mdns",
	"pair",
	"pull",
	"push",
	"reboot",
	"record",
	"reconnect",
	"remount",
	"reverse",
	"root",
	"shell",
	"shot",
	"sideload",
	"start-server",
	"sync",
	"tcpip",
	"uninstall",
	"unroot",
	"usb",
	"version",
	"wait-for-device",
	"wait-for-disconnect",
	"wait-for-recovery",
	"wait-for-rescue",
	"wait-for-sideload",
}
